def p(g):
 d='[o0eLlseJzLlYAkL]YzMlYAklseVzkLQzRXVzkSPzRLZMUPzkN]YzULPekN]seJeMlseVAkMQKMNPeULQeMM]YKRXFHKkXJekL]seVANNPeBKMPALNQzSLZkL]YKMLPAkN]YeMRQzNLQALLQekR]YeMSCVzNXJzkM]YANlYzkSCVzUXFHzklYKLNPzSXVeNNQAkRQAMlYzLNQeNlseJekM]seJANMCVKkMPeRLCVekM]WVeLMQeNRQzLUZLSPzklseJABKXFDeRNQALlWVKMXFDeMN]YzkRQARLTzMMPKkNCVALLPzLMQeLM]WVALMPKMXJAMSPeSNQeLN]YzMNQekU]WVAMLZNlYzSMTALNTzNLZklseVekRQzNlYeNN]WVekN]YeUMQAMMQeRUZMlYeSSZRMPeML]YzNRPAUMPzBKXFHAMNPeBKLPeURPeLRQKkMQANUPekS]YAMLQeMUQeSMCVzSXFHeSXJzkL]WVekSQKLLPeBKXJeLL]YKkLQKSXFHzkNCVeNMCVAMMPANLQAkM]YKklWVzLXJKkUZLRPAMRPeSlYeNBKPeNL]YAUXVeSMTAMXJekBKQARMTAklWVeLLQzNMQzNNQzNSPeNSQzRNTANLZkUQKkSPeUNCVANMPzNUPKkRPeRSZMSTAkLCVeMLQAkSCVANXJzMUPKNMPeLUQKNLPARNTzLMPzLLCVKkNPeMBKTzMLPALMCVeUMPzUMTASXFHAkRPAULZMMCVzNNPANSZMNCVeSNPzLSPzkUQeSUPzMLQKMMPeUSZNLCVeUNTAkSPASLPKLXJeRlWVAkNCVzkUPASNTKLXFDeUlYKNXJeNM]WVeNRZkBKPANRPeBKNPKUXFHzMXVeRNZLlYeSLQzMSZSLPASMTzkMQANNCVARXFDARXVKNXFDeSRTzkRPzUXVzLLPzSNZRXJzMMQeRMCVAUXFHeBKXFDAkBKPeNUQeLSQeRRTAkUZNSPKLMZRLZLNQeLBKPKNNZUXVKkLPAMUPASXVeULPAkUQALUTzLNPALSPzUNTzMNTzNMPAMNQeUUTALXJzMRPALRZNUPzkBKTzRXFDzLRZMRPzRMZLUPAUNGu]'
 m=[['Te','Z'],['WJ','Y'],['ly','X'],['xa','W'],['kH','V'],['dK','U'],['GH','T'],['BA','S'],['Bz','R'],['CJ','Q'],['GD','P'],['dz','N'],['dA','M'],['Be','L'],['gg','K'],['kD','J'],['w1','H'],['CF','G'],['Ea','F'],['df','E'],['w0','D'],[']y','C'],['c1','B'],['ag','A'],['ga','z'],['xf','y'],['sf','x'],['vo','w'],['u,','v'],['t}','u'],['l]','t'],['r2','s'],['qj','r'],['pO','q'],["b'",'p'],['nj','o'],['mI','n'],["{'",'m'],['k]','l'],['de','k'],['i[','j'],['h[','i'],["':",'h'],[',1','g'],[',2','f'],['aa','e'],['c0','d'],['b[','c'],['],','b'],[',0','a']]
 for r in m:
  d=d.replace(r[1],r[0])
 d=eval(d)
 for k in d:
  if k['I']==g:
   g=k['O']
   return g