def p(g):
 d='[zbKgd0fbKgd0fpDYTfVHJdnfJuLjfbKLjDVfZNHXnfXKWoK5DTfYQHvbKLjfbKLjDYZNHbbcJuWRJuWXnDZVfTHbKgd0fbKgd0fpDYTfVHvbKLjfbKLjDYZNHbKLjfbKLjfpDYTfNHbbcJdjfRJdjfXnDZVfNHRRd0fRRd0fpDTfTfVHbKLjfRRiWXK5DZTfQHJdnfJugiWbKgi5DVfZQHRJdjfRJdjfpDTfVfNHvbKgiWbKgi5DYZQHvXKWXK5DZYQHXnfXKWoK5DTfYQHXKWRRiWbKLjDTfZTHbKLjfbKgiWoK5DYTfQHbbcJcd0fRJcd0fXnDZVfVHRJuWRJuWpDTfVfTHJuLjfJuLjfpDVfTfNHJugd0fJugd0fpDVfTfVHbKgiWRRiWXnDZTfTHoKWXKWXnDZYTHbbcJuWRJuWXnDZVfTHJugiWJugiWpDVfTfTHbKLjfRXjfXnDZTfNHvRXjfRXjDZZNHJdnfJdKWoK5DVfYQHJdbcd0fJugd0fbKLjDVfZVHbKgd0fRRd0fXnDZTfVHXnfRXjfbKLjDTfZNHJdnfJdnfpDVfYNHXKWXKWpDTfYTHoKWRRiWRXjDZZTHJcJdjfJcJuWoK5DVfVfQHobcd0fXbcd0fXnDZYVHobcd0fbKgd0fbKLjDYZVHbbcJdjfbbcJdjfpDYVfNHbKgiWbKgiWpDYTfTHvRRiWRRi5DZZQHXnfXnfpDTfYNHbbcJcd0fbbcJcd0fpDYVfVHRJcd0fRJcd0fpDTfVfVHoKWoKWpDYYTHvvpDYYNHXnfRRiWbKgi5DTfZQHJcJcd0fJcJcd0fpDVfVfVHXbcd0fXbcd0fpDTfYVHJdKWJugiWbKLjDVfZTHvoKWoK5DYYQHJcJuWJcJuWpDVfVfTHRJdjfRJuWoK5DTfVfQHbbcJdjfbbcJuWoK5DYVfQHbbcJdjfRJuWXK5DZVfQHRXjfRRiWoK5DTfTfQHbbcJuWbbcJuWpDYVfTHJdnfJuLjfbKLjDVfZNHobcd0fobcd0fpDYYVHJuLjfJugiWoK5DVfTfQHXbcd0fRRd0fbKLjDTfZVHJdKWJdKWpDVfYTHoKWbKgiWbKLjDYZTHJdbcd0fJdbcd0fpDVfYVHvXnfXnDZYNHobcd0fRRd0fRXjDZZVHRRiWRRiWpDTfTfTHJcJdjfJcJdjfpDVfVfNHRXjfRXjfpDTfTfNF]'
 m=[['Qf','Z'],['Nf','Y'],['iL','X'],['5f','W'],['U3','V'],['tt','U'],['S8','T'],['ss','S'],['ig','R'],['P4','Q'],['rr','P'],['M2','N'],['qq','M'],['ad','L'],['bu','K'],['dc','J'],['Gz','H'],['F,','G'],['E}','F'],[']]','E'],['Cm','D'],['BO','C'],["A'",'B'],[']e','A'],['yv','z'],['xm','y'],['wI','x'],["{'",'w'],['pf','v'],['ci','u'],['3,','t'],['8,','s'],['4,','r'],['2,','q'],['on','p'],['bh','o'],['hj','n'],['l[','m'],['k[','l'],["':",'k'],['a5','j'],['gc','i'],['bd','h'],['ac','g'],['e[','f'],['],','e'],['cb','d'],['0,','c'],['aa','b'],['5,','a']]
 for r in m:
  d=d.replace(r[1],r[0])
 d=eval(d)
 for k in d:
  if k['I']==g:
   g=k['O']
   return g