def p(g):
 d='[RdakdakdakdakdakdaWjcldzjzgezcdljcZ,RrakrakrakrakrakrakrakraWBclrzBzcdueCjzcrlBcZ,RfrnrnrnrnrnrnrnrnrnrnrnrnrnrnrWoBlfrlojqcsCotgcrHjEcbaEgeEcdHBtgACJqAdzoBZ,RfdndndndndndndndndndndndndWojlfdlJqACBtgcdHeEcbHjtgcrCoqcszojZ,RKppppppppaWoclfzozcrujaDeCcduBzAlocZ,RfKKKKKKKKKKKKKKKKKfaWooclffzoozAruojCcsvoHcrEgjaEmeaEgcdEgBHAvJCAduoBzAfloocZ,RrkrkrkrkrkrkrWBlrljqcbCeqcdzBZ,RfrprprprprprprprprprprprprprprpraWoBclfrzoBzAduJCAvBHcdEgeaEgjHcrvoCcsuojzArloBcZ,RfLLLLLLLLLFsaWoJclfszoJzAfuoBCAdvJHAEgBaEgcdmvmeamvmjaEgcrEgoHcsvojCAruoozAsloJcZ,RfdpdpdpdpdpdpdpdpdpdpdpdpdpdaWojclfdzojzcsuoCcrvjHgeHcdvBCAuJzAdlojcZ,RfMMMMMMMMMMMMMMMMfWoolffloBqAdCJtgAHBEcdaEgemvgcbaEgjEcrHotgcsCojqArzooZ,RMnnnnnnnWolflBqcdCetgcbCjqcrzoZ,RFbpbpbpbpbpbpbpbpbpbpbaWJclszJzAuBCcdveHjCcruozcslJcZ,RGbnbnbnbnbnbnbnbnbnbWJlsloqcrCjtgcbHetgcdCBqAzJZ,RfNNNNNNNNNsWoJlfslooqArCojtgcsHoEcraEgjmvgcbamvmemvgcdaEgBEAHJtgAdCoBqAfzoJZ,RdkdkdkdkdWjldleqcbzjZ]'
 m='Y}ZX]Y3]XVyWUOVT"UShT0]SQyRPIQ{"PGGNfnMFFLfpKoeJavHsnGspFmDEqmDauCjeBcfAalzx[yw[x":wtmvqgumltfbsdbrglqanpjjokfnggm3il0ikeejh[i],hcagddfccebbd3,caab0,a'
 m=[[m[i:i+2],m[i+2]]for i in range(0,len(m),3)]
 for r in m:d=d.replace(r[1],r[0])
 d=eval(d)
 for k in d:
  if k['I']==g:g=k['O'];return g