# best: 65(xsot ovs att joking mewheni, 4atj sisyphus luke Seek, jailctf merger) / others: 66(natte), 75(mukundan), 79(dbdr), 87(MasukenSamba), 91(jacekw)
# lambda g:(k:=                      )and[s[::-k]for s in g[::k]]
# lambda g:(k:=1+g[0].index([s[0]for s in g if {*s}=={s[0]}][0]))and[s[::-k]for s in g[::k]]
# lambda g:(k:=[i+1for i,v in enumerate(g[0])if v!=g[0][0]][0])and[s[::-k]for s in g[::k]]
# lambda g:(k:=[i+1for i,s in enumerate(g)if{*s}=={s[0]}][0])and[s[::-k]for s in g[::k]]
# lambda g:[[y for x,y in zip([10]+t,t)if x!=y][::-2]for s,t in zip([0]+g,g)if s!=t][::2]
# lambda g:(k:=[i+1for i in range(8)if g[0]!=g[i]][0])and[s[::-k]for s in g[::k]]
# lambda g:[[s[::-k]for s in g[::k]]for k in range(1,8)if g[0]!=g[k-1]][0]
# lambda g:[[s[::-k]for s in g[::k]]for k in(3,4,5,6)if g[0]!=g[k-1]][0]
# lambda g:[[s[::-k]for s in g[::k]]for k in b""if g[0]!=g[k-1]][0]
# ============================== 65 =============================
# lambda g:(k:=1+g.index(min(g,key=set)))and[s[::-k]for s in g[::k]]
# f p(g):k=1+g.index(min(g,key=set));return[s[::-k]for s in g[::k]]
# lambda g,c=2:[r*0!=0and p(r,-2)or r for r in g if g!=(g:=r)][::c]
p=lambda g:[r*0!=0and p(r)[::-1]or r for r in g if g!=(g:=r)][::2]
